name: ⚙️ Test pumapy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]  # macos-latest, windows-latest,
        python-version: ['3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install apt dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libdbus-1-3 libxkbcommon-x11-0 \
            libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 \
            libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 \
            x11-utils libxcb-cursor0 libopengl0 libegl1-mesa
      - name: Install conda dependencies
        run: |
          conda env create --name packaging101 python pip conda-forge::pyside6
          conda init bash
          source ~/.bashrc
          conda activate packaging101
          python -m  pip install -e .
          python -c "import packaging101"
      - name: Test with pytest
        working-directory: ./tests
        run: |
          conda init bash
          source ~/.bashrc
          conda activate packaging101
          pytest
